### ISSUE TITLE
Doesn't compile against erlang/otp 18

### ISSUE THREAD

**Issue by ContentSafe** [travelping/regine#2]
I wasn't able to build regine with the newest version of erlang/otp

==> regine (compile)
src/regine_server.erl:89: type dict() undefined
ERROR: compile failed while processing [...]/regine: rebar_abort
** (Mix) Could not compile dependency regine, rebar command failed. If you want to recompile this dependency, please run: mix deps.compile regine

the reason seems to be the deprecation of the dict() type

**Comment by rixmann** [comment]
+1 same problem here

**Comment by RoadRunnr** [comment]
fixed in 0.2.1 some 3 month aog.
